# Workflow name
name: deploy-workload

# Triggers
on: [workflow_dispatch]

# Variables
env:
    resource_group_name: rg-cop2940-test-eus-app
    aci_prefix: ci-cop2940-test-eus-001
    runner_image: ghcr.io/colindembovsky/ubuntu-actions-runner:6d7a59dfa95ec094a5fa8292bad01158c374e3ad

# Jobs
jobs:
  deploy_infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Bicep File
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_id }}
        resourceGroupName: ${{ env.resource_group_name }}
        template: ./infrastructure/main.bicep

  deploy_self_hosted_runner:
    needs: deploy_infrastructure
    name: Deploy Ephemeral Runner    
    runs-on: ubuntu-latest
    steps:

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Runner
      run: |
        az container create \
          -g ${{ env.resource_group_name }} \
          -n ${{ env.aci_prefix }}-${{ github.run_id }} \
          --image ${{ env.runner_image }} \
          --restart-policy Never \
          --subnet /subscriptions/991ab2d9-e387-49a4-9cb5-a2f3127f3bb0/resourceGroups/rg-cop2940-test-eus-app/providers/Microsoft.Network/virtualNetworks/vnet-cop2940-test-eus-001/subnets/snet-cop2940-test-eus-containerInstance \
          --environment-variables \
            RUNNER_REPOSITORY_URL=https://github.com/${{ github.repository }} \
            GITHUB_TOKEN=${{ secrets.PAT }} \
            RUNNER_OPTIONS="--ephemeral" \
            RUNNER_NAME=${{ env.aci_prefix }}-${{ github.run_id }}

  delete_self_hosted_runner:
    needs: deploy_self_hosted_runner
    name: Delete Self-Hosted Runner
    runs-on: ubuntu-latest
    steps:

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete Runner
      run: |
        az container delete -g ${{ env.resource_group_name }} -n ${{ env.aci_prefix }}-${{ github.run_id }} --yes